travis:
  secure:
    BINSTAR_TOKEN: u35diCGm9I+Di/gESBX4o4ouDKyCUIihT6KrrPWT0jqxpCIKj1tlfsmMjIuegLY8twnlurwMqV/gQkvpbcXTlfPjZBdwoETPxkgObiTBb5FMnFAENlJXgFdNvLRJ6obYb1EsfPRc8BNGxSIWjCGiTiEEUDp7Q1gxuQcXl5LWouzKdFrNIun5dbmvVJyBCumZtAgRIQvfc4/W7Y5PgJEZ79jziyeZW/AJMFyoV3ncO2OIlkpRdpAuhUH31aOzSjSb9G3AXabi563z+PnSw9QRztU7NigEz87d/JsdLm755rRKf78/ZjBuTGUuSRi6jYXFff0H2bdGfZQEQkfqyW6ie4RkKDUo8sPXh4hUznfirrTbsFTOY19owG/OlD0LciDfBn40yh+4oMvN/e/yM1eQ9tPEwcezTUdyJOc+YLCO8Jy4LR5e1dp6aDmAL4NgIybOQyOapH+PSWflLKO6n8CffY0eORE97MwqUDmpM7Y8Y5WAJd7kGxbqSkJYHRzL255J/KpO3UHgIXtJ6OXLU46mSq3uSyLB/daUelmmhKGLtjBW0V3tF+nq0lfLLerBfyWVQsKyEeXvyNIjTNiLTbNdAhtQMZAvRuHBx2vx+PzyTWIoPvbD44KW5ZdUHa0PoS8TsrtF1UMtk9YHedV7pRs+hGa+QPRLAWvkh3cNy3F8BRY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
